/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 68
#define YY_END_OF_BUFFER 69
static yyconst short int yy_accept[323] =
    {   0,
       32,   32,   69,   67,   66,   64,   65,   67,   58,   46,
       67,   40,   41,   56,   54,   37,   55,   38,   57,   32,
       32,   36,   39,   50,   53,   49,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   44,   45,   42,   43,   66,   65,    0,   33,    0,
       33,    0,    0,    0,   30,    0,   32,   32,    0,    0,
        0,    0,    0,    0,    0,    0,   48,    0,   32,   32,
       52,   47,   51,   35,   35,   35,   35,   35,    9,   35,
       35,   35,    4,   35,   20,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,    0,    0,   30,

        0,    0,   30,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   31,   35,
       35,   35,   35,   35,   35,    6,   35,   35,   35,   35,
       10,   35,   35,   21,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,    0,    0,    0,    0,    0,    0,
        0,   31,    0,    0,    0,   49,   50,    0,    0,   60,
        0,   31,   31,   31,   31,   16,   35,   35,   35,   35,
        5,   35,   35,   35,   11,   35,    3,   35,   35,   35,
       26,   35,   35,   35,    7,    8,   35,    0,    0,    0,
        0,    0,    0,    0,   30,   31,   31,   31,   31,   59,

       62,    0,    0,   61,    0,    0,   31,    0,   31,   31,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       22,   35,   35,   35,   35,   13,    0,    0,    0,    0,
        0,    0,    0,   30,   30,   30,   30,   30,    0,   31,
        0,   31,   31,   63,   34,    0,   31,    0,   35,   35,
       35,   35,   35,   35,   35,   19,   35,   35,   35,   18,
       14,   15,    0,    0,    0,    0,    0,   30,   30,   30,
       30,   30,   30,   30,    0,   31,    0,    0,    0,    0,
        0,    0,   35,   27,   35,   35,   35,   35,   25,   28,
       24,    1,    0,    0,   30,   30,   30,    0,   30,    0,

        0,    0,    0,    0,    0,    0,    0,   35,   12,   35,
       17,    2,    0,   30,    0,    0,    0,    0,   29,   23,
        0,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,    1,    1,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   25,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   46,   47,   25,
       48,    1,   49,    1,   25,    1,   24,   25,   26,   27,

       28,   29,   30,   31,   50,   25,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       47,   25,   51,    1,   52,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[53] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    1,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    1,    3,
        1,    1
    } ;

static yyconst short int yy_base[327] =
    {   0,
        0,    0,  730,  731,  727,  731,    0,  723,  731,  731,
      719,  731,  731,  731,  731,   39,   41,   66,  704,   45,
       49,  731,  731,  703,  702,  701,    0,   37,   33,   35,
      679,   43,   23,   47,  684,  677,   40,  691,  690,   45,
      686,  731,  731,  731,  731,  714,    0,  710,  709,  705,
      704,   64,  696,   70,   87,   92,  695,   98,  673,  669,
      683,   65,   69,   84,  666,  665,  731,   81,  100,  105,
      731,  731,  731,    0,  663,  679,   89,  667,    0,  660,
      673,  663,    0,  659,  652,  655,  651,  653,  644,  634,
       87,   94,  104,  639,  638,  619,   97,  640,  115,  731,

      117,  121,  123,  635,  133,  135,  139,  620,  128,  606,
      618,  616,  611,  603,  134,  573,  593,  556,  146,  570,
      554,  550,  543,  554,  550,    0,  549,  537,  539,  535,
        0,  129,  526,    0,  515,  503,  506,  498,  488,  480,
      493,  480,  485,  476,  148,  152,  163,  491,  167,  169,
      175,  182,  482,  478,  443,  731,  731,  438,  461,  731,
      435,  184,  191,  203,  210,    0,  436,  423,  139,  414,
        0,  406,  175,  132,    0,  419,    0,  399,  398,  395,
        0,  400,  391,  401,    0,    0,  396,  218,  194,  225,
      233,  240,  216,  245,  252,  254,  264,  281,  288,  731,

      731,  389,  394,  731,  385,  380,  271,  238,  298,  305,
      360,  355,  344,  331,  209,  334,  330,  313,  328,  301,
        0,  300,  272,  261,  249,    0,  286,  313,  320,  328,
      332,  339,  347,  359,  256,  376,  384,  367,  272,  390,
      290,  401,  408,  731,  731,  351,  415,  425,  243,  219,
      206,  289,  201,  342,  189,    0,  192,  174,  163,    0,
        0,    0,  429,  437,  444,  449,  453,  326,  463,  471,
      478,  483,  490,  497,  502,  509,  516,  520,  393,  528,
      535,  547,  160,    0,  155,  141,  140,  113,    0,    0,
        0,    0,  540,  551,  555,  562,  569,  574,  578,  585,

      456,  592,  599,  611,  617,  624,  631,   87,    0,   55,
        0,    0,  604,  636,  643,  650,  657,  664,    0,    0,
      671,  731,  689,  692,  695,   83
    } ;

static yyconst short int yy_def[327] =
    {   0,
      322,    1,  322,  322,  322,  322,  323,  324,  322,  322,
      325,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  322,  322,  322,  322,  322,  323,  324,  324,  325,
      325,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  322,  322,  322,

      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,

      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  322,  322,  322,  322,  322,  322,  322,  322,

      322,  322,  322,  322,  322,  322,  322,  326,  326,  326,
      326,  326,  322,  322,  322,  322,  322,  322,  326,  326,
      322,    0,  322,  322,  322,  322
    } ;

static yyconst short int yy_nxt[784] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   27,   28,   29,   30,   31,   27,
       27,   32,   33,   34,   27,   35,   36,   37,   27,   38,
       39,   40,   27,   27,   41,   27,   27,   42,   43,   32,
       44,   45,   52,   56,   86,   53,   54,   57,   58,   68,
       75,   69,   69,   68,   78,   70,   70,   76,   80,   79,
       81,   83,   86,   77,   87,   95,   91,   84,   85,   92,
       98,   99,   78,   88,  101,   74,  102,  102,   55,   59,
      320,   96,  111,   60,   61,   62,  113,  119,  119,   63,

      103,   64,   65,  104,  105,   52,  112,   66,   53,   54,
      114,  115,  106,  100,  107,  107,   69,   69,  135,   68,
      116,   70,   70,  122,  123,  136,  319,  138,  144,  145,
      137,  146,  146,  147,  147,  101,  135,  102,  102,  148,
      149,   55,   72,  136,  139,  140,  144,  150,   67,  151,
      151,  152,  152,  106,  312,  107,  107,  162,   56,  162,
      176,  217,  163,  164,  188,  188,  145,  218,  146,  146,
      213,  154,  158,  165,  189,  311,  189,  310,  176,  190,
      191,  193,  309,  194,  194,  195,  195,  308,  213,  150,
      192,  151,  151,  196,   56,  196,   56,  292,  197,  198,

      206,  207,  162,   56,  162,  208,  216,  163,  164,  199,
       53,  231,  100,  291,  162,   56,  162,  208,  165,  209,
      210,  162,   56,  162,  216,  290,  206,  207,  289,  227,
      165,  227,  234,  234,  228,  229,  189,  287,  189,  101,
      253,  190,  191,  100,  189,  230,  189,  101,  285,  232,
      233,  189,  192,  189,  248,  248,   53,  231,  253,  193,
      192,  194,  194,  235,  284,  235,   56,  100,  236,  237,
      239,  240,  104,  272,  100,  196,   56,  196,  241,  238,
      197,  198,  100,   56,  283,  208,  241,  246,  247,  100,
      262,  199,  196,   56,  196,  241,  261,  242,  243,  196,

       56,  196,   98,  263,  239,  240,  277,  277,  199,  162,
       56,  162,  208,  260,  209,  210,  162,   56,  162,  208,
      286,  209,  210,  259,  227,  165,  227,  145,  258,  228,
      229,  227,  165,  227,  145,  100,  264,  265,  286,  227,
      230,  227,  148,  295,   98,  263,  101,  230,  266,  267,
      189,  257,  189,  101,  256,  232,  233,  255,  189,  254,
      189,  101,  100,  232,  233,  208,  192,  278,  278,  100,
      268,  252,  268,  288,  192,  269,  270,  100,  235,  251,
      235,  100,  250,  104,  272,  249,  271,  235,  100,  235,
      150,  288,  236,  237,  208,  235,  100,  235,  150,  245,

      273,  274,   56,  238,  241,   56,  275,  276,  244,  206,
      305,  238,  196,   56,  196,  241,  205,  242,  243,  196,
       56,  196,  241,  226,  242,  243,  225,   56,  199,  208,
      224,  246,  247,  223,  222,  199,  279,   56,  279,  221,
      220,  280,  281,  145,  219,  293,  294,  215,  227,  214,
      227,  145,  282,  264,  265,  227,  212,  227,  145,  211,
      264,  265,  205,  101,  230,  102,  102,  101,   56,  266,
      267,  230,  239,  315,  268,  204,  268,  193,  100,  269,
      270,  203,  268,  202,  268,  193,  100,  296,  297,  268,
      271,  268,  201,  100,  148,  295,  200,  150,  271,  298,

      299,  235,  100,  235,  150,  193,  273,  274,  235,  187,
      235,  150,  186,  273,  274,  185,  241,  238,  300,  300,
      184,   56,  183,  241,  238,  275,  276,  301,   56,  301,
      182,  181,  302,  303,  208,  180,  278,  278,  179,  279,
       56,  279,  208,  304,  280,  281,  279,   56,  279,  208,
      178,  306,  307,  177,  145,  282,  146,  146,  279,   56,
      279,  175,  282,  206,  305,  145,  174,  293,  294,  193,
      173,  313,  314,  268,  172,  268,  193,  171,  296,  297,
      268,  170,  268,  193,  169,  296,  297,  168,  150,  271,
      151,  151,  150,  167,  298,  299,  271,  166,  161,  241,

      100,  300,  300,  301,   56,  301,  241,  160,  302,  303,
      301,   56,  301,  241,  159,  316,  317,  157,  193,  304,
      194,  194,  301,   56,  301,   71,  304,  239,  315,   56,
      156,  208,   73,  246,  318,  279,   56,  279,  208,  155,
      306,  307,  279,   56,  279,  208,  153,  306,  307,  150,
      193,  282,  313,  314,  145,   56,  143,  241,  282,  275,
      321,  301,   56,  301,  241,  142,  316,  317,  301,   56,
      301,  241,  141,  316,  317,  134,   56,  304,  208,  133,
      246,  318,  132,   56,  304,  241,  131,  275,  321,   47,
      130,   47,   48,  129,   48,   50,  128,   50,  127,  126,

      125,  124,  121,  120,  118,  117,  110,  109,  108,  106,
      101,   51,   51,   49,   49,   46,   97,   94,   93,   90,
       89,   82,   73,   72,   71,   67,   51,   49,   46,  322,
        3,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322
    } ;

static yyconst short int yy_chk[784] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,   16,   17,   33,   16,   16,   17,   17,   20,
       28,   20,   20,   21,   29,   21,   21,   28,   30,   29,
       30,   32,   33,   28,   34,   40,   37,   32,   32,   37,
       52,   52,   29,   34,   54,  326,   54,   54,   16,   18,
      310,   40,   62,   18,   18,   18,   63,   68,   68,   18,

       55,   18,   18,   55,   55,   56,   62,   18,   56,   56,
       63,   64,   58,   52,   58,   58,   69,   69,   91,   70,
       64,   70,   70,   77,   77,   92,  308,   93,   97,   99,
       92,   99,   99,  101,  101,  102,   91,  102,  102,  103,
      103,   56,  109,   92,   93,   93,   97,  105,  115,  105,
      105,  106,  106,  107,  288,  107,  107,  119,  119,  119,
      132,  174,  119,  119,  145,  145,  146,  174,  146,  146,
      169,  109,  115,  119,  147,  287,  147,  286,  132,  147,
      147,  149,  285,  149,  149,  150,  150,  283,  169,  151,
      147,  151,  151,  152,  152,  152,  162,  259,  152,  152,

      162,  162,  163,  163,  163,  163,  173,  163,  163,  152,
      189,  189,  147,  258,  164,  164,  164,  164,  163,  164,
      164,  165,  165,  165,  173,  257,  165,  165,  255,  188,
      164,  188,  193,  193,  188,  188,  190,  253,  190,  190,
      215,  190,  190,  189,  191,  188,  191,  191,  251,  191,
      191,  192,  190,  192,  208,  208,  192,  192,  215,  194,
      191,  194,  194,  195,  250,  195,  196,  188,  195,  195,
      196,  196,  235,  235,  190,  197,  197,  197,  197,  195,
      197,  197,  191,  207,  249,  207,  239,  207,  207,  192,
      225,  197,  198,  198,  198,  198,  224,  198,  198,  199,

      199,  199,  227,  227,  199,  199,  241,  241,  198,  209,
      209,  209,  209,  223,  209,  209,  210,  210,  210,  210,
      252,  210,  210,  222,  228,  209,  228,  228,  220,  228,
      228,  229,  210,  229,  229,  227,  229,  229,  252,  230,
      228,  230,  268,  268,  230,  230,  231,  229,  231,  231,
      232,  219,  232,  232,  218,  232,  232,  217,  233,  216,
      233,  233,  228,  233,  233,  246,  232,  246,  246,  229,
      234,  214,  234,  254,  233,  234,  234,  230,  238,  213,
      238,  231,  212,  238,  238,  211,  234,  236,  232,  236,
      236,  254,  236,  236,  206,  237,  233,  237,  237,  205,

      237,  237,  240,  236,  240,  279,  240,  240,  203,  279,
      279,  237,  242,  242,  242,  242,  202,  242,  242,  243,
      243,  243,  243,  187,  243,  243,  184,  247,  242,  247,
      183,  247,  247,  182,  180,  243,  248,  248,  248,  179,
      178,  248,  248,  263,  176,  263,  263,  172,  264,  170,
      264,  264,  248,  264,  264,  265,  168,  265,  265,  167,
      265,  265,  161,  266,  264,  266,  266,  267,  301,  267,
      267,  265,  301,  301,  269,  159,  269,  269,  263,  269,
      269,  158,  270,  155,  270,  270,  264,  270,  270,  271,
      269,  271,  154,  265,  271,  271,  153,  272,  270,  272,

      272,  273,  267,  273,  273,  148,  273,  273,  274,  144,
      274,  274,  143,  274,  274,  142,  275,  273,  275,  275,
      141,  276,  140,  276,  274,  276,  276,  277,  277,  277,
      139,  138,  277,  277,  278,  137,  278,  278,  136,  280,
      280,  280,  280,  277,  280,  280,  281,  281,  281,  281,
      135,  281,  281,  133,  293,  280,  293,  293,  282,  282,
      282,  130,  281,  282,  282,  294,  129,  294,  294,  295,
      128,  295,  295,  296,  127,  296,  296,  125,  296,  296,
      297,  124,  297,  297,  123,  297,  297,  122,  298,  296,
      298,  298,  299,  121,  299,  299,  297,  120,  118,  300,

      294,  300,  300,  302,  302,  302,  302,  117,  302,  302,
      303,  303,  303,  303,  116,  303,  303,  114,  313,  302,
      313,  313,  304,  304,  304,  113,  303,  304,  304,  305,
      112,  305,  111,  305,  305,  306,  306,  306,  306,  110,
      306,  306,  307,  307,  307,  307,  108,  307,  307,  104,
      314,  306,  314,  314,   98,  315,   96,  315,  307,  315,
      315,  316,  316,  316,  316,   95,  316,  316,  317,  317,
      317,  317,   94,  317,  317,   90,  318,  316,  318,   89,
      318,  318,   88,  321,  317,  321,   87,  321,  321,  323,
       86,  323,  324,   85,  324,  325,   84,  325,   82,   81,

       80,   78,   76,   75,   66,   65,   61,   60,   59,   57,
       53,   51,   50,   49,   48,   46,   41,   39,   38,   36,
       35,   31,   26,   25,   24,   19,   11,    8,    5,    3,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\lexical-analyser.l"
#define INITIAL 0
/*Definition Section*/
#line 3 ".\\lexical-analyser.l"
    #include<stdio.h>
    #include<string.h>
    #include "scanner.h" /* this file contains all tokens */
    
/*Rule Section*/
/* defining some regular expression */
#line 651 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 24 ".\\lexical-analyser.l"


#line 805 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 323 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 731 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 26 ".\\lexical-analyser.l"
return kw_PROGRAM;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 27 ".\\lexical-analyser.l"
return kw_IMPLICIT;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 28 ".\\lexical-analyser.l"
return kw_NONE;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 29 ".\\lexical-analyser.l"
return kw_IF;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 30 ".\\lexical-analyser.l"
return kw_ELSE;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 31 ".\\lexical-analyser.l"
return kw_END;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 32 ".\\lexical-analyser.l"
return kw_THEN;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 33 ".\\lexical-analyser.l"
return kw_TYPE;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 34 ".\\lexical-analyser.l"
return kw_DO;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 35 ".\\lexical-analyser.l"
return kw_LEN;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 36 ".\\lexical-analyser.l"
return kw_KIND;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 37 ".\\lexical-analyser.l"
return kw_CONTINUE;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 38 ".\\lexical-analyser.l"
return kw_GOTO;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 39 ".\\lexical-analyser.l"
return kw_RETURN;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 40 ".\\lexical-analyser.l"
return kw_SELECT;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 41 ".\\lexical-analyser.l"
return kw_CASE;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 42 ".\\lexical-analyser.l"
return kw_FUNCTION;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 43 ".\\lexical-analyser.l"
return kw_RESULT;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 44 ".\\lexical-analyser.l"
return kw_INTENT;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 45 ".\\lexical-analyser.l"
return kw_IN;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 46 ".\\lexical-analyser.l"
return kw_OUT;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 47 ".\\lexical-analyser.l"
return kw_PRINT;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 48 ".\\lexical-analyser.l"
return kw_DIMENSION;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 49 ".\\lexical-analyser.l"
return kw_POINTER;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 51 ".\\lexical-analyser.l"
return dt_INT;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 52 ".\\lexical-analyser.l"
return dt_REAL;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 53 ".\\lexical-analyser.l"
return dt_COMPLEX;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 54 ".\\lexical-analyser.l"
return dt_LOGICALS;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 55 ".\\lexical-analyser.l"
return dt_CHARACTER;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 57 ".\\lexical-analyser.l"
return ct_COMPLEX;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 58 ".\\lexical-analyser.l"
return ct_REAL;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 59 ".\\lexical-analyser.l"
return ct_INT;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 60 ".\\lexical-analyser.l"
return ct_CHARACTER;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 61 ".\\lexical-analyser.l"
return ct_LOGICALS;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 62 ".\\lexical-analyser.l"
return IDENTIFIER;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 64 ".\\lexical-analyser.l"
return sp_COLON;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 65 ".\\lexical-analyser.l"
return sp_COMMA;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 66 ".\\lexical-analyser.l"
return sp_STOP;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 67 ".\\lexical-analyser.l"
return sp_SEMICOLON;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 68 ".\\lexical-analyser.l"
return sp_LB;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 69 ".\\lexical-analyser.l"
return sp_RB;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 70 ".\\lexical-analyser.l"
return sp_CURLYLB;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 71 ".\\lexical-analyser.l"
return sp_CURLYRB;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 72 ".\\lexical-analyser.l"
return sp_SQUARELB;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 73 ".\\lexical-analyser.l"
return sp_SQUARERB;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 74 ".\\lexical-analyser.l"
return sp_AND;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 76 ".\\lexical-analyser.l"
return op_EQUALITY;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 77 ".\\lexical-analyser.l"
return op_NOTEQUALITY;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 78 ".\\lexical-analyser.l"
return op_GREATER;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 79 ".\\lexical-analyser.l"
return op_LESSER;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 80 ".\\lexical-analyser.l"
return op_GREATEREQUAL;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 81 ".\\lexical-analyser.l"
return op_LESSEREQUAL;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 82 ".\\lexical-analyser.l"
return op_EQUAL;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 83 ".\\lexical-analyser.l"
return op_ADD;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 84 ".\\lexical-analyser.l"
return op_SUB;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 85 ".\\lexical-analyser.l"
return op_MUL;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 86 ".\\lexical-analyser.l"
return op_DIV;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 87 ".\\lexical-analyser.l"
return op_MODULUS;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 88 ".\\lexical-analyser.l"
return op_AND;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 89 ".\\lexical-analyser.l"
return op_OR;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 90 ".\\lexical-analyser.l"
return op_NOT;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 91 ".\\lexical-analyser.l"
return op_EQV;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 92 ".\\lexical-analyser.l"
return op_NEQV;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 93 ".\\lexical-analyser.l"
return nl;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 94 ".\\lexical-analyser.l"
return COMMENT;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 95 ".\\lexical-analyser.l"
;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 96 ".\\lexical-analyser.l"
return inval ;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 98 ".\\lexical-analyser.l"
ECHO;
	YY_BREAK
#line 1228 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 323 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 323 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 322);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 98 ".\\lexical-analyser.l"


/*call the yywrap function*/
int yywrap()								
{
	return 1;
}
/*Auxiliary function*/
int main(void)
{
    int token;
    int yylineno = 1 ;
    int countChar=0;
    int prevLine=0;

    // file handling
    extern FILE *yyin, *yyout;
    yyin = fopen("input.txt", "r");  
    yyout = fopen("output.txt", "w");  

    // some temporary variables  
    char buffer[40] = {0}; 
    char buffer3[16] = {0}; 
    char buffer2;
    fputs(" Line No --          ",yyout);
    fputs("Tokens --           ",yyout);
    fputs("Lexemes --           \n",yyout);
    token = yylex();
    while(token){
        if (token!=30){
            // Retrieving all token through their defined numbers
            if(token==1)
            {
                    sprintf(buffer, "%s", "kw_PROGRAM");
            }
            else if(token==2)
                    {
                    sprintf(buffer, "%s", "kw_IMPLICIT");
            }
            else if(token==3)
                    {
                    sprintf(buffer, "%s", "kw_NONE");
            }
            else if(token==4)
                    {
                    sprintf(buffer, "%s", "dt_REAL");
            }
            else if(token==5)
                    {
                    sprintf(buffer, "%s", "IDENTIFIER");
            }
            else if(token==6)
                    {
                    sprintf(buffer, "%s", "sp_COLON");
            }
            else if(token==7)
                    {
                    sprintf(buffer, "%s", "sp_SEMICOLON");
            }
            else if(token==8)
                    {
                    sprintf(buffer, "%s", "op_EQUAL");
            }
            else if(token==9)
                    {
                    sprintf(buffer, "%s", "op_ADD");
            }
            else if(token==10)
                    {
                    sprintf(buffer, "%s", "op_SUB");
            }
            else if(token==11)
                    {
                    sprintf(buffer, "%s", "op_MUL");
            }
            else if(token==12)
                    {
                    sprintf(buffer, "%s", "op_DIV");
            }
            else if(token==13)
                    {
                    sprintf(buffer, "%s", "op_EQUALITY");
            }
            else if(token==14)
                    {
                    sprintf(buffer, "%s", "op_RELATIONAL");
            }
            else if(token==15)
                    {
                    sprintf(buffer, "%s", "kw_IF");
            }
            else if(token==16)
                    {
                    sprintf(buffer, "%s", "kw_ELSE");
            }
            else if(token==17)
                    {
                    sprintf(buffer, "%s", "kw_END");
            }
            else if(token==18)
                    {
                    sprintf(buffer, "%s", "kw_THEN");
            }
            else if(token==19)
                    {
                    sprintf(buffer, "%s", "kw_TYPE");
            }
            else if(token==20)
                    {
                    sprintf(buffer, "%s", "dt_INT");
            }
            else if(token==21)
                    {
                    sprintf(buffer, "%s", "dt_COMPLEX");
            }
            else if(token==22)
                    {
                    sprintf(buffer, "%s", "dt_LOGICALS");
            }
            else if(token==23)
                    {
                    sprintf(buffer, "%s", "dt_CHARACTER");
            }
            else if(token==24)
                    {
                    sprintf(buffer, "%s", "sp_LB");
            }
            else if(token==25)
                    {
                    sprintf(buffer, "%s", "sp_RB");
            }
            else if(token==26)
                    {
                    sprintf(buffer, "%s", "sp_CURLYLB");
            }
            else if(token==27)
                    {
                    sprintf(buffer, "%s", "sp_CURLYRB");
            }
            else if(token==28)
                    {
                    sprintf(buffer, "%s", "sp_SQUARELB");
            }
            else if(token==29)
                    {
                    sprintf(buffer, "%s", "sp_SQUARERB");
            }
            else if(token==31)
                    {
                    sprintf(buffer, "%s", "kw_DO");
            }
            else if(token==32)
                    {
                    sprintf(buffer, "%s", "kw_LEN");
            }
            else if(token==33)
                    {
                    sprintf(buffer, "%s", "kw_KIND");
            }
            else if(token==34)
                    {
                    sprintf(buffer, "%s", "kw_CONTINUE");
            }
            else if(token==35)
                    {
                    sprintf(buffer, "%s", "kw_GOTO");
            }
            else if(token==36)
                    {
                    sprintf(buffer, "%s", "kw_RETURN");
            }
            else if(token==37)
                    {
                    sprintf(buffer, "%s", "kw_SELECT");
            }
            else if(token==38)
                    {
                    sprintf(buffer, "%s", "kw_CASE");
            }
            else if(token==39)
                    {
                    sprintf(buffer, "%s", "kw_FUNCTION");
            }
            else if(token==40)
                    {
                    sprintf(buffer, "%s", "kw_RESULT");
            }
            else if(token==41)
                    {
                    sprintf(buffer, "%s", "kw_INTENT");
            }
            else if(token==42)
                    {
                    sprintf(buffer, "%s", "kw_IN");
            }
            else if(token==43)
                    {
                    sprintf(buffer, "%s", "kw_OUT");
            }
            else if(token==44)
                    {
                    sprintf(buffer, "%s", "ct_INT");
            }
            else if(token==45)
                    {
                    sprintf(buffer, "%s", "ct_REAL");
            }
            else if(token==46)
                    {
                    sprintf(buffer, "%s", "ct_CHARACTER");
            }
            else if(token==47)
                    {
                    sprintf(buffer, "%s", "ct_COMPLEX");
            }
            else if(token==48)
                    {
                    sprintf(buffer, "%s", "ct_LOGICALS");
            }
            else if(token==49)
                    {
                    sprintf(buffer, "%s", "sp_COMMA");
            }
            else if(token==50)
                    {
                    sprintf(buffer, "%s", "sp_STOP");
            }
            else if(token==51)
                    {
                    sprintf(buffer, "%s", "kw_PRINT");
            }
            else if(token==52)
                    {
                    sprintf(buffer, "%s", "op_MODULUS");
            }       
            else if(token==53)
                    {
                    sprintf(buffer, "%s", "inval");
            }
            else if(token==54)
            {
                    sprintf(buffer, "%s", "COMMENT");
            }
            else if(token==55)
                        {
                        sprintf(buffer, "%s", "op_NOTEQUALITY");
                }
                else if(token==56)
                        {
                        sprintf(buffer, "%s", "op_GREATER");
                }
                else if(token==57)
                        {
                        sprintf(buffer, "%s", "op_LESSER");
                }
                else if(token==58)
                        {
                        sprintf(buffer, "%s", "op_GREATEREQUAL");
                }
                else if(token==59)
                        {
                        sprintf(buffer, "%s", "op_LESSEREQUAL");
                }
                else if(token==60)
                        {
                        sprintf(buffer, "%s", "op_AND");
                }
                else if(token==61)
                        {
                        sprintf(buffer, "%s", "op_OR");
                }
                else if(token==62)
                        {
                        sprintf(buffer, "%s", "op_NOT");
                }
                else if(token==63)
                        {
                        sprintf(buffer, "%s", "op_EQV");
                }
                else if(token==64)
                        {
                        sprintf(buffer, "%s", "op_NEQV");
                }
                else if(token==65)
                {
                        sprintf(buffer, "%s", "kw_DIMENSION");
                }
                else if(token==66)
                        {
                        sprintf(buffer, "%s", "kw_POINTER");
                }
                else if(token==67)
                {
                        sprintf(buffer, "%s", "sp_AND");
                }
            else{
                sprintf(buffer, "%d", token);
            }


// Writing into File start

        if (prevLine==yylineno){            
            fputs(" ",yyout);
        }
        else{
             fputs("\n ",yyout);
        }
        prevLine=yylineno;

 // Since our language is case insensitive we converting all the UpperCase character into LowerCase character
                sprintf(buffer3, "%d", yylineno);
                fputs(buffer3,yyout);
                countChar=strlen(buffer3);

                while(countChar<20){
                     fputs(" ",yyout);
                        countChar++;
                }
                countChar=0;


                fputs(buffer,yyout);
                countChar=strlen(buffer);

                while(countChar<20){
                     fputs(" ",yyout);
                        countChar++;
                }
                countChar=0;
        // Conversion Start
            for(int i=0;i<strlen(yytext);i++){
                int temp=yytext[i];
                if (temp>64 && temp<91 && token!=46){
                    temp+=32;
                    buffer2=temp;
                    sprintf(buffer3,"%c",buffer2);
                    fputs(buffer3,yyout);
                }
                else{
                    buffer2=temp;
                    sprintf(buffer3,"%c",buffer2);
                    fputs(buffer3,yyout);
                }
                countChar++;
             }
                while(countChar<20){
                        fputs(" ",yyout);
                        countChar++;
                }
                countChar=0;
        // Conversion end

                

                
                fputs("\n",yyout);
// Writing into file end

        }
        else{

        // increasing count of line when new line detected or when token = 30
        yylineno++;

        }

        //  calling function again to find another lexeme
        token = yylex();

    }
	
	return 0;
}
