
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 68
#define YY_END_OF_BUFFER 69
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[267] =
    {   0,
       32,   32,   69,   67,   66,   64,   65,   67,   58,   46,
       67,   40,   41,   56,   54,   37,   55,   38,   57,   32,
       32,   36,   39,   50,   53,   49,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   44,   45,   42,   43,   66,   65,    0,   33,    0,
       33,    0,    0,   30,    0,    0,    0,    0,    0,    0,
        0,    0,   48,    0,   32,   32,   52,   47,   51,   35,
       35,   35,   35,   35,    9,   35,   35,   35,    4,   35,
       20,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,   31,   35,
       35,   35,   35,   35,   35,    6,   35,   35,   35,   35,
       10,   35,   35,   21,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,    0,    0,    0,    0,    0,    0,
       49,   50,    0,    0,   60,    0,   31,    0,   31,   31,
       31,   16,   35,   35,   35,   35,    5,   35,   35,   35,
       11,   35,    3,   35,   35,   35,   26,   35,   35,   35,
        7,    8,   35,    0,    0,    0,    0,   30,   30,   59,
       62,    0,    0,   61,    0,    0,   31,    0,   31,   31,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,

       22,   35,   35,   35,   35,   13,    0,    0,    0,   30,
       30,   30,   30,   63,   34,    0,   31,    0,   35,   35,
       35,   35,   35,   35,   35,   19,   35,   35,   35,   18,
       14,   15,    0,    0,   30,   30,   30,    0,    0,    0,
        0,    0,   35,   27,   35,   35,   35,   35,   25,   28,
       24,    1,    0,   30,    0,    0,    0,   35,   12,   35,
       17,    2,    0,   29,   23,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,    1,    1,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   25,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   46,   47,   25,
       48,    1,   49,    1,   25,    1,   24,   25,   26,   27,

       28,   29,   30,   31,   50,   25,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       47,   25,   51,    1,   52,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[53] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    1,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    1,    3,
        1,    1
    } ;

static const flex_int16_t yy_base[271] =
    {   0,
        0,    0,  486,  487,  483,  487,    0,  479,  487,  487,
      475,  487,  487,  487,  487,   36,  487,   63,  460,   40,
       44,  487,  487,  459,  458,  457,    0,   32,   28,   30,
      435,   38,   38,   40,  440,  433,   35,  447,  446,   48,
      442,  487,  487,  487,  487,  470,    0,  466,  465,  461,
      460,  452,   65,   67,  430,  426,  440,   48,   61,   70,
      423,  422,  487,   84,   91,   95,  487,  487,  487,    0,
      420,  436,   79,  424,    0,  417,  430,  420,    0,  417,
      412,  417,  416,  421,  414,  407,   72,   74,   92,  414,
      419,  408,   85,  101,  108,  430,  112,  417,  105,  409,

      427,  426,  425,  424,  106,  396,  422,  393,  124,  407,
      394,  395,  390,  403,  402,    0,  403,  394,  399,  399,
        0,   96,  397,    0,  388,  387,  392,  387,  377,  376,
      390,  381,  387,  378,  136,  114,  140,  394,  391,  364,
      487,  487,  358,  383,  487,  367,  126,  142,  153,  160,
      177,    0,  364,  347,  119,  343,    0,  332,  129,  126,
        0,  340,    0,  321,  314,  310,    0,  304,  295,  306,
        0,    0,  300,  165,  184,  191,  199,  487,  208,  487,
      487,  297,  302,  487,  298,  294,  214,  167,  225,  233,
      282,  274,  264,  245,  168,  257,  252,  229,  243,  236,

        0,  235,  202,  199,  191,    0,  206,  240,  248,  252,
      260,  267,  275,  487,  487,  279,  286,  293,  188,  168,
      164,  178,  167,  241,  157,    0,  159,  147,  145,    0,
        0,    0,  297,  301,  305,  312,  319,  324,  331,  340,
      347,  359,  148,    0,  135,  110,  104,   54,    0,    0,
        0,    0,  328,  352,  365,  372,  379,   54,    0,   45,
        0,    0,  386,    0,    0,  487,  407,  410,  413,   68
    } ;

static const flex_int16_t yy_def[271] =
    {   0,
      266,    1,  266,  266,  266,  266,  267,  268,  266,  266,
      269,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  266,  266,  266,  266,  266,  267,  268,  268,  269,
      269,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  266,  266,  266,  266,  266,  266,  266,

      266,  266,  266,  266,  266,  266,  266,  266,  266,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,

      270,  270,  270,  270,  270,  270,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  266,  266,  266,  266,  266,  270,  270,  270,
      270,  270,  266,  270,  270,    0,  266,  266,  266,  266
    } ;

static const flex_int16_t yy_nxt[540] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   27,   28,   29,   30,   31,   27,
       27,   32,   33,   34,   27,   35,   36,   37,   27,   38,
       39,   40,   27,   27,   41,   27,   27,   42,   43,   32,
       44,   45,   52,   53,   64,   71,   65,   65,   64,   74,
       66,   66,   72,   76,   75,   77,   79,   83,   73,   82,
       70,   87,   80,   81,   88,  101,   84,   74,   91,   94,
      265,   95,   95,   96,   97,   54,   55,   82,  103,  102,
       56,   57,   58,  264,   92,  262,   59,  105,   60,   61,

      109,  109,  104,  125,   62,  126,  106,   65,   65,   64,
      127,   66,   66,  112,  113,  128,  134,  135,  135,   68,
       63,  125,   94,  126,   95,   95,  136,  162,  137,  137,
      179,  179,  129,  130,  134,  147,  148,  147,  148,  261,
      149,  150,  186,  187,  143,  162,  260,  174,  139,  174,
      193,  151,  175,  176,  136,  197,  137,  137,   52,   53,
      196,  198,  259,  177,  147,  148,  147,  188,  193,  149,
      150,  147,  148,  147,  188,  258,  189,  190,  196,  252,
      151,   52,  207,  218,  218,  178,  251,  151,  147,  148,
      147,   54,  250,  186,  187,  174,  249,  174,   94,  223,

      175,  176,  174,  247,  174,   94,  245,  208,  209,  246,
      174,  177,  174,  244,  178,   52,  207,  223,  177,  210,
       94,  210,  233,  234,  211,  212,  148,  246,  188,  243,
      216,  217,  232,  178,  231,  213,  147,  148,  147,  188,
      178,  189,  190,  230,  147,  148,  147,  188,  178,  189,
      190,  174,  151,  174,   94,  178,  208,  209,  229,  174,
      151,  174,   94,  228,  208,  209,  227,  177,   96,  235,
      226,  210,  248,  210,  136,  177,  211,  212,  210,  225,
      210,  136,  224,  236,  237,  222,  210,  213,  210,  178,
      248,   96,  235,  188,  213,  238,  238,  178,  148,  221,

      188,  220,  216,  217,  239,  148,  239,  219,  188,  240,
      241,   94,  215,   95,   95,   94,  214,  233,  234,  136,
      242,  253,  254,  210,  185,  210,  136,  206,  236,  237,
      210,  205,  210,  136,  204,  236,  237,  203,  188,  213,
      238,  238,  136,  148,  137,  137,  213,  186,  255,  202,
      178,  239,  148,  239,  188,  201,  240,  241,  239,  148,
      239,  188,  200,  256,  257,  199,  136,  242,  253,  254,
      239,  148,  239,  195,  242,  186,  255,  148,  194,  188,
      192,  216,  263,  239,  148,  239,  188,  191,  256,  257,
      239,  148,  239,  188,  185,  256,  257,  184,  148,  242,

      188,  183,  216,  263,  182,  181,  242,   47,  180,   47,
       48,  173,   48,   50,  172,   50,  171,  170,  169,  168,
      167,  166,  165,  164,  163,  161,  160,  159,  158,  157,
      156,  155,  154,  153,  152,  146,  145,  144,  142,   67,
      141,   69,  140,  138,  136,  133,  132,  131,  124,  123,
      122,  121,  120,  119,  118,  117,  116,  115,  114,  111,
      110,  108,  107,  100,   99,   98,   94,   51,   51,   49,
       49,   46,   93,   90,   89,   86,   85,   78,   69,   68,
       67,   63,   51,   49,   46,  266,    3,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,

      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266
    } ;

static const flex_int16_t yy_chk[540] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,   16,   16,   20,   28,   20,   20,   21,   29,
       21,   21,   28,   30,   29,   30,   32,   34,   28,   33,
      270,   37,   32,   32,   37,   58,   34,   29,   40,   53,
      260,   53,   53,   54,   54,   16,   18,   33,   59,   58,
       18,   18,   18,  258,   40,  248,   18,   60,   18,   18,

       64,   64,   59,   87,   18,   88,   60,   65,   65,   66,
       88,   66,   66,   73,   73,   89,   93,   94,   94,   99,
      105,   87,   95,   88,   95,   95,   97,  122,   97,   97,
      136,  136,   89,   89,   93,  109,  109,  109,  147,  247,
      109,  109,  147,  147,  105,  122,  246,  135,   99,  135,
      155,  109,  135,  135,  137,  160,  137,  137,  148,  148,
      159,  160,  245,  135,  149,  149,  149,  149,  155,  149,
      149,  150,  150,  150,  150,  243,  150,  150,  159,  229,
      149,  174,  174,  188,  188,  135,  228,  150,  151,  151,
      151,  148,  227,  151,  151,  175,  225,  175,  175,  195,

      175,  175,  176,  223,  176,  176,  221,  176,  176,  222,
      177,  175,  177,  220,  174,  177,  177,  195,  176,  179,
      207,  179,  207,  207,  179,  179,  187,  222,  187,  219,
      187,  187,  205,  175,  204,  179,  189,  189,  189,  189,
      176,  189,  189,  203,  190,  190,  190,  190,  177,  190,
      190,  208,  189,  208,  208,  207,  208,  208,  202,  209,
      190,  209,  209,  200,  209,  209,  199,  208,  210,  210,
      198,  211,  224,  211,  211,  209,  211,  211,  212,  197,
      212,  212,  196,  212,  212,  194,  213,  211,  213,  208,
      224,  213,  213,  216,  212,  216,  216,  209,  217,  193,

      217,  192,  217,  217,  218,  218,  218,  191,  186,  218,
      218,  233,  185,  233,  233,  234,  183,  234,  234,  235,
      218,  235,  235,  236,  182,  236,  236,  173,  236,  236,
      237,  170,  237,  237,  169,  237,  237,  168,  238,  236,
      238,  238,  253,  239,  253,  253,  237,  239,  239,  166,
      234,  240,  240,  240,  240,  165,  240,  240,  241,  241,
      241,  241,  164,  241,  241,  162,  254,  240,  254,  254,
      242,  242,  242,  158,  241,  242,  242,  255,  156,  255,
      154,  255,  255,  256,  256,  256,  256,  153,  256,  256,
      257,  257,  257,  257,  146,  257,  257,  144,  263,  256,

      263,  143,  263,  263,  140,  139,  257,  267,  138,  267,
      268,  134,  268,  269,  133,  269,  132,  131,  130,  129,
      128,  127,  126,  125,  123,  120,  119,  118,  117,  115,
      114,  113,  112,  111,  110,  108,  107,  106,  104,  103,
      102,  101,  100,   98,   96,   92,   91,   90,   86,   85,
       84,   83,   82,   81,   80,   78,   77,   76,   74,   72,
       71,   62,   61,   57,   56,   55,   52,   51,   50,   49,
       48,   46,   41,   39,   38,   36,   35,   31,   26,   25,
       24,   19,   11,    8,    5,    3,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,

      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexical-analyser.l"
/*Definition Section*/
#line 3 "lexical-analyser.l"
    #include<stdio.h>
    #include<string.h>
    #include "scanner.h" /* this file contains all tokens */
    
#line 652 "lex.yy.c"
/*Rule Section*/
/* defining some regular expression */
#line 655 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 24 "lexical-analyser.l"


#line 875 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 267 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 487 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 26 "lexical-analyser.l"
return kw_PROGRAM;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 27 "lexical-analyser.l"
return kw_IMPLICIT;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 28 "lexical-analyser.l"
return kw_NONE;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 29 "lexical-analyser.l"
return kw_IF;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 30 "lexical-analyser.l"
return kw_ELSE;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 31 "lexical-analyser.l"
return kw_END;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 32 "lexical-analyser.l"
return kw_THEN;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 33 "lexical-analyser.l"
return kw_TYPE;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 34 "lexical-analyser.l"
return kw_DO;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 35 "lexical-analyser.l"
return kw_LEN;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 36 "lexical-analyser.l"
return kw_KIND;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 37 "lexical-analyser.l"
return kw_CONTINUE;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 38 "lexical-analyser.l"
return kw_GOTO;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 39 "lexical-analyser.l"
return kw_RETURN;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 40 "lexical-analyser.l"
return kw_SELECT;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 41 "lexical-analyser.l"
return kw_CASE;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 42 "lexical-analyser.l"
return kw_FUNCTION;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 43 "lexical-analyser.l"
return kw_RESULT;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 44 "lexical-analyser.l"
return kw_INTENT;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 45 "lexical-analyser.l"
return kw_IN;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 46 "lexical-analyser.l"
return kw_OUT;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 47 "lexical-analyser.l"
return kw_PRINT;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 48 "lexical-analyser.l"
return kw_DIMENSION;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 49 "lexical-analyser.l"
return kw_POINTER;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 51 "lexical-analyser.l"
return dt_INT;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 52 "lexical-analyser.l"
return dt_REAL;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 53 "lexical-analyser.l"
return dt_COMPLEX;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 54 "lexical-analyser.l"
return dt_LOGICALS;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 55 "lexical-analyser.l"
return dt_CHARACTER;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 57 "lexical-analyser.l"
return ct_COMPLEX;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 58 "lexical-analyser.l"
return ct_REAL;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 59 "lexical-analyser.l"
return ct_INT;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 60 "lexical-analyser.l"
return ct_CHARACTER;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 61 "lexical-analyser.l"
return ct_LOGICALS;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 62 "lexical-analyser.l"
return IDENTIFIER;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 64 "lexical-analyser.l"
return sp_COLON;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 65 "lexical-analyser.l"
return sp_COMMA;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 66 "lexical-analyser.l"
return sp_STOP;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 67 "lexical-analyser.l"
return sp_SEMICOLON;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 68 "lexical-analyser.l"
return sp_LB;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 69 "lexical-analyser.l"
return sp_RB;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 70 "lexical-analyser.l"
return sp_CURLYLB;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 71 "lexical-analyser.l"
return sp_CURLYRB;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 72 "lexical-analyser.l"
return sp_SQUARELB;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 73 "lexical-analyser.l"
return sp_SQUARERB;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 74 "lexical-analyser.l"
return sp_AND;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 76 "lexical-analyser.l"
return op_EQUALITY;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 77 "lexical-analyser.l"
return op_NOTEQUALITY;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 78 "lexical-analyser.l"
return op_GREATER;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 79 "lexical-analyser.l"
return op_LESSER;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 80 "lexical-analyser.l"
return op_GREATEREQUAL;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 81 "lexical-analyser.l"
return op_LESSEREQUAL;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 82 "lexical-analyser.l"
return op_EQUAL;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 83 "lexical-analyser.l"
return op_ADD;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 84 "lexical-analyser.l"
return op_SUB;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 85 "lexical-analyser.l"
return op_MUL;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 86 "lexical-analyser.l"
return op_DIV;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 87 "lexical-analyser.l"
return op_MODULUS;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 88 "lexical-analyser.l"
return op_AND;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 89 "lexical-analyser.l"
return op_OR;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 90 "lexical-analyser.l"
return op_NOT;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 91 "lexical-analyser.l"
return op_EQV;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 92 "lexical-analyser.l"
return op_NEQV;
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 93 "lexical-analyser.l"
return nl;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 94 "lexical-analyser.l"
return COMMENT;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 95 "lexical-analyser.l"
;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 96 "lexical-analyser.l"
return inval ;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 98 "lexical-analyser.l"
ECHO;
	YY_BREAK
#line 1273 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 267 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 267 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 266);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 98 "lexical-analyser.l"


/*call the yywrap function*/
int yywrap()								
{
	return 1;
}
/*Auxiliary function*/
int main(void)
{
    int token;
    int yylineno = 1 ;
    int countChar=0;
    int prevLine=0;

    // file handling
    extern FILE *yyin, *yyout;
    yyin = fopen("input.txt", "r");  
    yyout = fopen("output.txt", "w");  

    // some temporary variables  
    char buffer[40] = {0}; 
    char buffer3[16] = {0}; 
    char buffer2;
    fputs(" Line No --          ",yyout);
    fputs("Tokens --           ",yyout);
    fputs("Lexemes --           \n",yyout);
    token = yylex();
    while(token){
        if (token!=30){
            // Retrieving all token through their defined numbers
            if(token==1)
            {
                    sprintf(buffer, "%s", "kw_PROGRAM");
            }
            else if(token==2)
                    {
                    sprintf(buffer, "%s", "kw_IMPLICIT");
            }
            else if(token==3)
                    {
                    sprintf(buffer, "%s", "kw_NONE");
            }
            else if(token==4)
                    {
                    sprintf(buffer, "%s", "dt_REAL");
            }
            else if(token==5)
                    {
                    sprintf(buffer, "%s", "IDENTIFIER");
            }
            else if(token==6)
                    {
                    sprintf(buffer, "%s", "sp_COLON");
            }
            else if(token==7)
                    {
                    sprintf(buffer, "%s", "sp_SEMICOLON");
            }
            else if(token==8)
                    {
                    sprintf(buffer, "%s", "op_EQUAL");
            }
            else if(token==9)
                    {
                    sprintf(buffer, "%s", "op_ADD");
            }
            else if(token==10)
                    {
                    sprintf(buffer, "%s", "op_SUB");
            }
            else if(token==11)
                    {
                    sprintf(buffer, "%s", "op_MUL");
            }
            else if(token==12)
                    {
                    sprintf(buffer, "%s", "op_DIV");
            }
            else if(token==13)
                    {
                    sprintf(buffer, "%s", "op_EQUALITY");
            }
            else if(token==14)
                    {
                    sprintf(buffer, "%s", "op_RELATIONAL");
            }
            else if(token==15)
                    {
                    sprintf(buffer, "%s", "kw_IF");
            }
            else if(token==16)
                    {
                    sprintf(buffer, "%s", "kw_ELSE");
            }
            else if(token==17)
                    {
                    sprintf(buffer, "%s", "kw_END");
            }
            else if(token==18)
                    {
                    sprintf(buffer, "%s", "kw_THEN");
            }
            else if(token==19)
                    {
                    sprintf(buffer, "%s", "kw_TYPE");
            }
            else if(token==20)
                    {
                    sprintf(buffer, "%s", "dt_INT");
            }
            else if(token==21)
                    {
                    sprintf(buffer, "%s", "dt_COMPLEX");
            }
            else if(token==22)
                    {
                    sprintf(buffer, "%s", "dt_LOGICALS");
            }
            else if(token==23)
                    {
                    sprintf(buffer, "%s", "dt_CHARACTER");
            }
            else if(token==24)
                    {
                    sprintf(buffer, "%s", "sp_LB");
            }
            else if(token==25)
                    {
                    sprintf(buffer, "%s", "sp_RB");
            }
            else if(token==26)
                    {
                    sprintf(buffer, "%s", "sp_CURLYLB");
            }
            else if(token==27)
                    {
                    sprintf(buffer, "%s", "sp_CURLYRB");
            }
            else if(token==28)
                    {
                    sprintf(buffer, "%s", "sp_SQUARELB");
            }
            else if(token==29)
                    {
                    sprintf(buffer, "%s", "sp_SQUARERB");
            }
            else if(token==31)
                    {
                    sprintf(buffer, "%s", "kw_DO");
            }
            else if(token==32)
                    {
                    sprintf(buffer, "%s", "kw_LEN");
            }
            else if(token==33)
                    {
                    sprintf(buffer, "%s", "kw_KIND");
            }
            else if(token==34)
                    {
                    sprintf(buffer, "%s", "kw_CONTINUE");
            }
            else if(token==35)
                    {
                    sprintf(buffer, "%s", "kw_GOTO");
            }
            else if(token==36)
                    {
                    sprintf(buffer, "%s", "kw_RETURN");
            }
            else if(token==37)
                    {
                    sprintf(buffer, "%s", "kw_SELECT");
            }
            else if(token==38)
                    {
                    sprintf(buffer, "%s", "kw_CASE");
            }
            else if(token==39)
                    {
                    sprintf(buffer, "%s", "kw_FUNCTION");
            }
            else if(token==40)
                    {
                    sprintf(buffer, "%s", "kw_RESULT");
            }
            else if(token==41)
                    {
                    sprintf(buffer, "%s", "kw_INTENT");
            }
            else if(token==42)
                    {
                    sprintf(buffer, "%s", "kw_IN");
            }
            else if(token==43)
                    {
                    sprintf(buffer, "%s", "kw_OUT");
            }
            else if(token==44)
                    {
                    sprintf(buffer, "%s", "ct_INT");
            }
            else if(token==45)
                    {
                    sprintf(buffer, "%s", "ct_REAL");
            }
            else if(token==46)
                    {
                    sprintf(buffer, "%s", "ct_CHARACTER");
            }
            else if(token==47)
                    {
                    sprintf(buffer, "%s", "ct_COMPLEX");
            }
            else if(token==48)
                    {
                    sprintf(buffer, "%s", "ct_LOGICALS");
            }
            else if(token==49)
                    {
                    sprintf(buffer, "%s", "sp_COMMA");
            }
            else if(token==50)
                    {
                    sprintf(buffer, "%s", "sp_STOP");
            }
            else if(token==51)
                    {
                    sprintf(buffer, "%s", "kw_PRINT");
            }
            else if(token==52)
                    {
                    sprintf(buffer, "%s", "op_MODULUS");
            }       
            else if(token==53)
                    {
                    sprintf(buffer, "%s", "inval");
            }
            else if(token==54)
            {
                    sprintf(buffer, "%s", "COMMENT");
            }
            else if(token==55)
                        {
                        sprintf(buffer, "%s", "op_NOTEQUALITY");
                }
                else if(token==56)
                        {
                        sprintf(buffer, "%s", "op_GREATER");
                }
                else if(token==57)
                        {
                        sprintf(buffer, "%s", "op_LESSER");
                }
                else if(token==58)
                        {
                        sprintf(buffer, "%s", "op_GREATEREQUAL");
                }
                else if(token==59)
                        {
                        sprintf(buffer, "%s", "op_LESSEREQUAL");
                }
                else if(token==60)
                        {
                        sprintf(buffer, "%s", "op_AND");
                }
                else if(token==61)
                        {
                        sprintf(buffer, "%s", "op_OR");
                }
                else if(token==62)
                        {
                        sprintf(buffer, "%s", "op_NOT");
                }
                else if(token==63)
                        {
                        sprintf(buffer, "%s", "op_EQV");
                }
                else if(token==64)
                        {
                        sprintf(buffer, "%s", "op_NEQV");
                }
                else if(token==65)
                {
                        sprintf(buffer, "%s", "kw_DIMENSION");
                }
                else if(token==66)
                        {
                        sprintf(buffer, "%s", "kw_POINTER");
                }
                else if(token==67)
                {
                        sprintf(buffer, "%s", "sp_AND");
                }
            else{
                sprintf(buffer, "%d", token);
            }


// Writing into File start

        if (prevLine==yylineno){            
            fputs(" ",yyout);
        }
        else{
             fputs("\n ",yyout);
        }
        prevLine=yylineno;

 // Since our language is case insensitive we converting all the UpperCase character into LowerCase character
                sprintf(buffer3, "%d", yylineno);
                fputs(buffer3,yyout);
                countChar=strlen(buffer3);

                while(countChar<20){
                     fputs(" ",yyout);
                        countChar++;
                }
                countChar=0;


                fputs(buffer,yyout);
                countChar=strlen(buffer);

                while(countChar<20){
                     fputs(" ",yyout);
                        countChar++;
                }
                countChar=0;
        // Conversion Start
            for(int i=0;i<strlen(yytext);i++){
                int temp=yytext[i];
                if (temp>64 && temp<91 && token!=46){
                    temp+=32;
                    buffer2=temp;
                    sprintf(buffer3,"%c",buffer2);
                    fputs(buffer3,yyout);
                }
                else{
                    buffer2=temp;
                    sprintf(buffer3,"%c",buffer2);
                    fputs(buffer3,yyout);
                }
                countChar++;
             }
                while(countChar<20){
                        fputs(" ",yyout);
                        countChar++;
                }
                countChar=0;
        // Conversion end

                

                
                fputs("\n",yyout);
// Writing into file end

        }
        else{

        // increasing count of line when new line detected or when token = 30
        yylineno++;

        }

        //  calling function again to find another lexeme
        token = yylex();

    }
	
	return 0;
}

