#define kw_PROGRAM  1 
#define kw_IMPLICIT 2 
#define kw_NONE 3 
#define dt_REAL 4 
#define IDENTIFIER 5 
#define sp_COLON 6 
#define sp_SEMICOLON 7 
#define op_EQUAL 8 
#define op_ADD 9 
#define op_SUB 10 
#define op_MUL 11 
#define op_DIV 12 
#define op_EQUALITY 13 
#define op_RELATIONAL 14 
#define kw_IF 15
