#define kw 1 //KEYWORD
#define spt 2 //SEPARATOR
#define idf 3 //IDENTIFIER
#define dt 4 //DATATYPE
#define ddt 5 //DERIVEDDATATYPE
#define stmt 6 //STATEMENT
#define opt 7 //OPERATOR
#define ifel 8 //IFELSE
#define iff 9 //IFF
#define swit 10 //SWITCH
#define whi 11 //WHILE
#define fo 12 //FOR
#define dowhi 13 //DOWHILE
#define fun 14 //FUNCTION
#define cmmts 15 //COMMENT
#define nu 16 //NUMBERS
#define ws 17 //WHITESPACE
#define inval 18 //INVALID
#define nl 19 //INVALID
