#define kw_PROGRAM  1 
#define kw_IMPLICIT 2 
#define kw_NONE 3 
#define dt_REAL 4 
#define IDENTIFIER 5 
#define sp_COLON 6 
#define sp_SEMICOLON 7 
#define op_EQUAL 8 
#define op_ADD 9 
#define op_SUB 10 
#define op_MUL 11 
#define op_DIV 12 
#define op_EQUALITY 13 
#define op_RELATIONAL 14 
#define kw_IF 15
#define kw_ELSE 16
#define kw_END 17
#define kw_THEN 18
#define kw_TYPE 19
#define dt_INT 20
#define dt_COMPLEX 21
#define dt_LOGICALS 22
#define dt_CHARACTER 23
#define sp_LB 24
#define sp_RB 25
#define sp_CURLYLB 26
#define sp_CURLYRB 27
#define sp_SQUARELB 28
#define sp_SQUARERB 29
#define nl 30